comment:
  behavior: "new"

flags:
  # filter the folder(s) you wish to measure by that flag
  authlogin:
    # only include files in the backend folder
    paths:
      - authlogin/
  monolith:
    paths:
      - src/
