version: '3'
services:      
  mco:
    build: .
    ports:
       - "81:80"
       - "444:443"
    volumes:
       - ./sockets:/sockets
    networks:
       - mco-network
    command: "npm start"

networks:
   mco-network:
