version: 2.1
orbs:
  node: circleci/node@1.0.0
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    executor:
      name: node/node
      tag: "8.15"
    steps:
      - checkout
      - run:
          name: Check Node Version
          command: $([ $(node -v) == 'v8.15.1' ])
      - run:
          name: Make fake certs
          command: |
            touch data/private_key.pem
            touch data/pub.key
            touch data/cert.pem

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run Tests
          command: npm run lint-test

      - codecov/upload:
          file: coverage/*.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

      - store_artifacts:
          path: coverage

workflows:
  version: 2.1
  build-test:
    jobs:
      - build
