version: 2.1
orbs:
  node: circleci/node@1.0.0
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    executor:
      name: node/node
      tag: "10.16.0"
    steps:
      - run:
          name: Hello
          command: echo Hello!
      - run:
          name: Dump some important envs
          command: |
            echo $CIRCLE_REPOSITORY_URL
            echo $CIRCLE_BRANCH
            echo $CIRCLE_SHA1
            echo $CIRCLE_PULL_REQUEST
      - run:
          name: Attempt manual checkout
          command: |
            bash <(curl -s https://gist.githubusercontent.com/drazisil/e97dc21454120251472154de1c1b1c7b/raw/5b20af0e79d9ba74e81ee1eb4b699af9cb880558/checkout.sh)
      - run:
          name: Did it work?
          command: ls

workflows:
  version: 2.1
  build-test:
    jobs:
      - build
