version: 2.1
orbs:
  node: circleci/node@1.0.0
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    executor:
      name: node/node
      tag: "10.16.0"
    steps:
      - run:
          name: Hello
          command: echo Hello!

workflows:
  version: 2.1
  build-test:
    jobs:
      - build
