version: 2.1
jobs:
  build_authlogin:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: |
            sudo make init
          working_directory: authlogin
      - run:
          name: Run tests
          command: |
            make test
          working_directory: authlogin
      - run:
          name: Upload coverage
          command: |
            ls -lah
            cd authlogin
            bash <(curl -s https://codecov.io/bash) -F authlogin -d > upload.txt
            bash <(curl -s https://codecov.io/bash) -F authlogin            
      - store_test_results:
          path: authlogin/test_results
      - store_artifacts:
          path: authlogin/upload.txt
      - store_artifacts:
          path: authlogin/htmlcov
      - store_artifacts:
          path: authlogin/coverage.xml
      - store_artifacts:
          path: authlogin/test_results

  build_main:
    docker: 
      - image: node:10.16.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Make fake certs
          command: |
            touch src/services/shared/data/private_key.pem
            touch src/services/shared/data/pub.key
            touch src/services/shared/data/cert.pem
      - run:
          name: Run Tests
          command: npm run lint-test
      - run:
          name: Upload coverage
          command: |
            bash <(curl -s https://codecov.io/bash) -F monolith
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

      - store_artifacts:
          path: coverage

workflows:
  build-test:
    jobs:
      - build_main
      - build_authlogin
