version: 2.1
orbs:
  node: circleci/node@1.0.0
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    executor:
      name: node/node
      tag: "8.15"
    steps:
      - checkout
      - prepare-artifacts-dir
      - node-version-check:
          version: "v8.15.1"
      - npm-outdated-check
      - run:
          name: Make fake certs
          command: |
            touch data/private_key.pem
            touch data/pub.key
            touch data/cert.pem

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run Tests
          command: npm run lint-test

      - codecov/upload:
          file: coverage/*.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

      - store_artifacts:
          path: coverage

commands:
  prepare-artifacts-dir:
    description: "Prepare and set artifacts directory path"
    parameters:
      artifacts-path:
        default: "$CIRCLE_WORKING_DIRECTORY/artifacts"
        type: string
    steps:
      - run:
          name: "Create artifacts path"
          command: |
            mkdir -p << parameters.report-path >>
            echo "export ARTIFACTS_PATH=<< parameters.report-path >>"" >> $BASH_ENV
      - run:
          name: "Echo artifacts path"
          command: |
            echo $ARTIFACTS_PATH
  npm-outdated-check:
    description: "Check for outdated versions of dependencies"
    parameters:
      report-path:
        default: "$CIRCLE_WORKING_DIRECTORY/artifacts"
        type: string
    steps:
      - run:
          name: "Check for outdated versions of dependencies"
          command: |
            npm outdated > << parameters.report-path >>/outdated_versions.txt
            $(npm outdated)
  node-version-check:
    description: "Check for version of Node"
    parameters:
      version:
        type: string
    steps:
      - run:
          name: "Check for version of Node"
          command: |
            node -v
            $([ $(node -v) == "<< parameters.version >>" ])

workflows:
  version: 2.1
  build-test:
    jobs:
      - build
